### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by djvanas** [Jerrythafast/se-logger#2]
Hi!

I’m having trouble extracting the key from my SolarEdge inverter. When I run the code it comes up with a Syntax error on the inverter ID. I have uses all possible inverter ID’s but can’t get it to work.

**Comment by Jerrythafast** [comment]
Hey! I presume you are using `get-key-by-rs232.py` and getting an error like this?
```
  File "get-key-by-rs232.py", line 25
    inverter_id = 0xYourSerialHere
                    ^
SyntaxError: invalid token
```
(The last line could also be `SyntaxError: invalid syntax` depending on what went wrong exactly.)

If so, some things that you could check:
- Always start with `inverter_id = 0x` (the `0x` is really important).
- Then, write the first 8 characters of your inverter ID (this will be a combination of digits and the letters A through F). **Don't** include the `-` and the two characters that come after it.

An example: if your SolarEdge inverter ID is 7653AB8C-43, you should enter `inverter_id = 0x7653AB8C` into the script.
