### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by slashw** [Jerrythafast/se-logger#5]
Dag Jerrythefast,
U heeft te maken met een complete noob op gebied van programmeren.
In uw config.sample.py heeft u het over deze te kopiëren naar config.py...
Nu de domme vraag, waar moet ik deze dan heen kopiëren/plaatsen? 
Ik loop hier vast op.
Met zoeken kom ik diverse van deze op mijn raspberry tegen.
Ik draai nu Raspbian.

BVD
WIm

**Comment by Jerrythafast** [comment]
Hoi slashw,

Het bestand `config.py` moet in dezelfde map staan als `liveupdate.py`. Dus bijvoorbeeld in `/opt/se-logger`. Als het goed is bestaat deze nog niet, als je het programma voor het eerst aan het installeren bent. 

Jerry

**Comment by slashw** [comment]
Top
Dankjewel

**Comment by slashw** [comment]
Dag Jerry,
Ik heb nog een vraag, wbt het sleutel ophalen.
Is het zo dat als ik get-key-by-rs232.py een paar keer doe, er steeds een andere sleutel voorbij komt? Ik doe dit omdat er nm erg veel dezelfde bijvoorbeeld achterelkaar\xbf\ in de key zitten. Weet niet of dit normaal is?
Of als ik de verbose opdracht doe?
Ik lees het uit via de rs485 poort. (Omvormer met display)
Had het een poosje proefdraaien, hier kreeg ik veel mysterious bytes! in de logger staan. Geen foutmelding.
Begrijp dat dan het juiste sleuteltje nog gevonden is?

Bvd
Wim

**Comment by Jerrythafast** [comment]
Hoi Wim,
Als het goed is krijg je elke keer dezelfde sleutel. In de sleutel die uit het script komt staat als het goed is 16 keer `\x..` met steeds twee andere tekens op de plaats van die twee puntjes. Als hierbij jou opvallend veel herhaling in zit klopt er misschien toch iets niet...
Jerry

**Comment by slashw** [comment]
Dag Jerry,
Klopt, 16 keer \x.. , maar dus niet dezelfde sleutel.
De tekens zijn ( na opvragen nieuwe key) wel elke keer anders, dus gaat er nog iets niet goed bij mij.
Af en toe zit er veel herhaling in het opvragen. Niet altijd.
Allerlei combinaties vanuit de omvormer met aansluiten gedaan (met en zonder aarde)
Als er voor mij weer meer tijd is, zal ik er mee verder aan.
Opgeven is nog geen optie.

In ieder geval bedankt voor je reactie...top
Wim

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op woensdag 20 mei 2020 14:01, Jerrythafast <notifications@github.com> schreef:
