### ISSUE TITLE
Update pvo-upload.php

### ISSUE THREAD

**Issue by k-van-man** [Jerrythafast/se-logger#7]
Hi Jerrythafast,

An update for pvoutput, because it accepts 
- no data older then 14 days
- no more then 30 lines max

$q = $db->query(
  'SELECT timestamp, p_active, temperature, v_ac, se_day ' .
  'FROM (' .
    'SELECT ' .
      'timestamp, p_active, temperature, v_ac, ' .
      '@curdate := FROM_UNIXTIME(timestamp, "%Y%m%d") date, ' .
      '@prevsum := IF(@prevdate = @curdate, @prevsum + de_day, de_day) se_day, ' .
      '@prevdate := @curdate date2 ' .
    'FROM telemetry_inverter ' .
    'JOIN (SELECT @prevsum := 0, @curdate := NULL, @prevdate := NULL) vars ' .
    'WHERE timestamp >= (SELECT IFNULL(UNIX_TIMESTAMP(FROM_UNIXTIME(pvo_last_live, "%Y%m%d")), 0) FROM live_update) ' .
    'ORDER BY timestamp' .
  ') x ' .
  'WHERE timestamp > (SELECT pvo_last_live FROM live_update) AND timestamp > UNIX_TIMESTAMP(now() - INTERVAL 14 DAY) ' .
  'LIMIT 30');

**Comment by Jerrythafast** [comment]
The restrictions you mentioned apply when you have not donated to PVOutput. I have added an option to turn on/off donation mode in the upload script to enforce the lower restrictions for those who need them.
