### ISSUE TITLE
Parsing problem with 3 phase inverter data 

### ISSUE THREAD

**Issue by willemx** [Jerrythafast/se-logger#8]
It seems that my inverter creates inverter messages of length 266, which results in these messages being ignored by the parser.
if I replace this line:
`elif type == 0x0011 and length in (200, 264):  # 3ph inverter`
by this one:
`elif type == 0x0011 and length in (200, 264, 266):  # 3ph inverter`
parsing seems to work again.

**Comment by Jerrythafast** [comment]
Thanks @willemx! It took a while for me to get to this, but I've just published this change as v0.0.17!
